sudo: required

services:
  - docker

before_install:
- sudo apt-get install -y --only-upgrade -o Dpkg::Options::=--force-confnew docker-engine
- sudo rm /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin
- docker network create example.com
- docker-compose up -d
- sleep 60

script:
- ./run_test.sh
