version: '2'
services:
  ldap:
    build: knox
    command: /ldap.sh

  knox:
    build: knox
    ports:
    - "8443:8443"
    command: /gateway.sh
    volumes:
     - ./topologies:/knox/conf/topologies
     - ./solr:/knox/data/services/solr
    depends_on:
    - ldap

  solr:
    image: solr:alpine
    ports:
    - "8983"
    - "9983"
    command: -c

